main/urls.py
from django.urls import path
from main import views
from .views import *

app_name = "main"
urlpatterns = [
    path('',views.showmain,name="showmain"),
    path('introduce/',views.introduce, name="introduce"),
    path('<str:id>',views.detail, name="detail"),
    path('create/',views.create, name="create"),
    path('update/<str:id>',views.update, name="update"),
    path('delete/<str:id>',views.delete, name="delete"),
    path('request_create/',views.request_create, name="request_create"),
    path('letter/',views.letter, name="letter"),
    path('feedback/',views.feedback, name="feedback"),
    path('board/',views.board, name="board"),
    path('board_new/',views.board_new, name="board_new"),
    path('board_detail/<str:id>',views.board_detail, name="board_detail"),
    path('board_edit/<str:id>',views.board_edit, name="board_edit"),
    path('board_update/<str:id>',views.board_update, name="board_update"),
    path('board_create/',views.board_create, name="board_create"),
    path('board_delete/<str:id>',views.board_delete, name="board_delete"),
    path('<str:board_id>/create_board_comment', create_board_comment, name="create_board_comment"),
    path('<str:board_comment_id>/edit_board_comment',edit_board_comment,name='edit_board_comment'),
    path('<str:board_comment_id>/update_board_comment',update_board_comment,name='update_board_comment'),
    path('<str:board_comment_id>/delete_board_comment',delete_board_comment,name='delete_board_comment'),
    path('feedback_create/',views.feedback_create, name="feedback_create"),
    path('like_toggle/<int:post_id>/', views.like_toggle, name="like_toggle"),
    path('career/',views.career, name="career"),
    path('sample/',views.sample, name="sample"),
    path('board_like_toggle/<int:post_id>/', views.board_like_toggle, name="board_like_toggle"),
    path('board_notice/',views.board_notice, name="board_notice"),
    path('disallowed_useragent/',views.disallowed_useragent, name="disallowed_useragent"),
]

nodoubt/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    #allauth의 url 연결
    path('accounts/', include('allauth.urls')),
    path('', include('main.urls')),
    path('users/', include('users.urls')),
]  + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views

app_name = "users"
urlpatterns = [
    path('mypage/', views.mypage, name="mypage"),
]

nodoubt/templates/shared/footer.html
<!-- Footer -->
<div class="footer">
    <div class="footer_letter">
        <h1 id="footer_content">취준생 여러분의 취업 성공을 응원합니다.</h1>
        <h1 id="footer_content">취준생들이 느낄 불편과 힘듦을</h1>
        <h1 id="footer_content">조금이나마 덜어주고 싶었습니다.</h1>
    </div>
    <div id="footer_link">
        <div>
            <a id="footer_company" href="{% url 'main:showmain' %}">NODOUBT</a>
        </div>
        <a href="{% url 'main:feedback' %}"><button>문의사항</button></a>
        <a href="{% url 'main:letter' %}"><button>개인정보 처리방침</button></a>
    </div>
</div>

nodoubt/templates/shared/navbar.html
{% load static %}
<div class="menu">
    <div class="menu_form menu_company">
        <a href="{% url 'main:showmain' %}">NODOUBT</a>
    </div>
    <div class="menu_form menu_right">
        <div class="dropdown dropdown_left">
            <i class="fas fa-user fa-lg dropbtn"></i>
            <div class="dropdown-content">
                {% if user.is_authenticated %}
                <a href="{% url 'users:mypage' %}">{{user.last_name}}{{user.first_name}} 님</a>
                <form id="nav_logout" method="POST" action="{% url 'account_logout' %}">
                    {% csrf_token %}
                    <a id="nav_logout_anchor">로그아웃</a>
                </form>
                <a class="dropdown-content_mycontent" href="{% url 'main:career' %}">내 컨텐츠</a>
                <a class="dropdown-content_mypage" href="{% url 'main:board' %}">자유게시판</a>
                {% else %}
                <a href="{% url 'account_login' %}">로그인</a>
                <a href="{% url 'account_signup' %}">회원가입</a>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% if user.is_authenticated %}
<script src="{% static 'js/dropdown_login.js' %}"></script>
<script>
    const mycontent = document.querySelector(".dropdown-content_mycontent");
    function mycontentReady(event){
        event.preventDefault();
        alert("서비스 준비 중입니다.");
    }
    mycontent.addEventListener("click", mycontentReady);
</script>
{% endif %}
<script src="{% static 'js/dropdown.js' %}"></script>