main/urls.py
from django.urls import path
from main import views
from .views import *

app_name = "main"
urlpatterns = [
    path('',views.showmain,name="showmain"),
    path('introduce/',views.introduce, name="introduce"),
    path('<str:id>',views.detail, name="detail"),
    path('create/',views.create, name="create"),
    path('update/<str:id>',views.update, name="update"),
    path('delete/<str:id>',views.delete, name="delete"),
    path('request_create/',views.request_create, name="request_create"),
    path('letter/',views.letter, name="letter"),
    path('feedback/',views.feedback, name="feedback"),
    path('board/',views.board, name="board"),
    path('board_new/',views.board_new, name="board_new"),
    path('board_detail/<str:id>',views.board_detail, name="board_detail"),
    path('board_edit/<str:id>',views.board_edit, name="board_edit"),
    path('board_update/<str:id>',views.board_update, name="board_update"),
    path('board_create/',views.board_create, name="board_create"),
    path('board_delete/<str:id>',views.board_delete, name="board_delete"),
    path('<str:board_id>/create_board_comment', create_board_comment, name="create_board_comment"),
    path('<str:board_comment_id>/edit_board_comment',edit_board_comment,name='edit_board_comment'),
    path('<str:board_comment_id>/update_board_comment',update_board_comment,name='update_board_comment'),
    path('<str:board_comment_id>/delete_board_comment',delete_board_comment,name='delete_board_comment'),
    path('feedback_create/',views.feedback_create, name="feedback_create"),
    path('like_toggle/<int:post_id>/', views.like_toggle, name="like_toggle"),
    path('career/',views.career, name="career"),
    path('sample/',views.sample, name="sample"),
    path('board_like_toggle/<int:post_id>/', views.board_like_toggle, name="board_like_toggle"),
    path('board_notice/',views.board_notice, name="board_notice"),
    path('disallowed_useragent/',views.disallowed_useragent, name="disallowed_useragent"),
]

nodoubt/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    #allauth의 url 연결
    path('accounts/', include('allauth.urls')),
    path('', include('main.urls')),
    path('users/', include('users.urls')),
]  + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views

app_name = "users"
urlpatterns = [
    path('mypage/', views.mypage, name="mypage"),
]

users/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Profile(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE)

users/views.py
from django.shortcuts import render
from main.models import Request
from django.contrib.auth.models import User
# Create your views here.

def mypage(request):
    user = request.user
    requests = Request.objects.filter(writer=user)
    return render(request, 'users/mypage.html',{'requests':requests})

users/templates/users/mypage.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="mypage">
    <h2 id="mypage_first_title">나의 글 목록</h2>
    <table class="mypage_first">
        <thead class="mypage_first_head">
            <tr>
                <th scope="col" class="mypage_first_head_th mypage_pubdate">작성일자</th>
                <th scope="col" class="mypage_first_head_th mypage_job_type">제목</th>
                <th scope="col" class="mypage_first_head_th mypage_name">작성자</th>
                <th scope="col" class="mypage_first_head_th mypage_email">내용</th>
            </tr>
        </thead>
        <tbody class="mypage_first_body">
            {% for board in boards %}
            <tr>
                <td class="mypage_first_body_td mypage_pubdate">{{board.pub_date}}</td>
                <td class="mypage_first_body_td mypage_job_type"><a href="{% url 'main:board_detail' board.id %}" target="_blank">{{board.title}}</a></td>
                <td class="mypage_first_body_td mypage_name">{{board.writer}}</td>
                <td class="mypage_first_body_td mypage_email">{{board.summary}}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock%}