main/urls.py
from django.urls import path
from main import views
from .views import *

app_name = "main"
urlpatterns = [
    path('',views.showmain,name="showmain"),
    path('introduce/',views.introduce, name="introduce"),
    path('<str:id>',views.detail, name="detail"),
    path('create/',views.create, name="create"),
    path('update/<str:id>',views.update, name="update"),
    path('delete/<str:id>',views.delete, name="delete"),
    path('request_create/',views.request_create, name="request_create"),
    path('letter/',views.letter, name="letter"),
    path('feedback/',views.feedback, name="feedback"),
    path('board/',views.board, name="board"),
    path('board_new/',views.board_new, name="board_new"),
    path('board_detail/<str:id>',views.board_detail, name="board_detail"),
    path('board_edit/<str:id>',views.board_edit, name="board_edit"),
    path('board_update/<str:id>',views.board_update, name="board_update"),
    path('board_create/',views.board_create, name="board_create"),
    path('board_delete/<str:id>',views.board_delete, name="board_delete"),
    path('<str:board_id>/create_board_comment', create_board_comment, name="create_board_comment"),
    path('<str:board_comment_id>/edit_board_comment',edit_board_comment,name='edit_board_comment'),
    path('<str:board_comment_id>/update_board_comment',update_board_comment,name='update_board_comment'),
    path('<str:board_comment_id>/delete_board_comment',delete_board_comment,name='delete_board_comment'),
    path('feedback_create/',views.feedback_create, name="feedback_create"),
    path('like_toggle/<int:post_id>/', views.like_toggle, name="like_toggle"),
    path('career/',views.career, name="career"),
    path('sample/',views.sample, name="sample"),
    path('board_like_toggle/<int:post_id>/', views.board_like_toggle, name="board_like_toggle"),
    path('board_notice/',views.board_notice, name="board_notice"),
    path('disallowed_useragent/',views.disallowed_useragent, name="disallowed_useragent"),
]

nodoubt/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    #allauth의 url 연결
    path('accounts/', include('allauth.urls')),
    path('', include('main.urls')),
    path('users/', include('users.urls')),
]  + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

main/models.py
from pyexpat import model
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Data(models.Model):
    id = models.AutoField(primary_key=True)
    company = models.CharField(max_length=200)
    job = models.CharField(max_length=100)
    employed_year = models.CharField(max_length=20)
    pub_date = models.DateTimeField()
    body = models.TextField()
    image = models.ImageField(upload_to = "data/", blank=True, null=True)
    like_user_set = models.ManyToManyField(User, blank=True, related_name='likes_user_set',through='Like')

    def __str__(self):
        return self.company

    @property
    def like_count(self):
        return self.like_user_set.count()

class Request(models.Model):
    EMPLOY_TYPE_CHOICES = {
        ('정규', '정규'),
        ('인턴', '인턴')
    }
    id = models.AutoField(primary_key=True)
    employ_type = models.CharField(max_length=20, choices=EMPLOY_TYPE_CHOICES)
    company_name = models.CharField(max_length=30)
    school_major = models.CharField(max_length=30)
    writer = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=20)
    email = models.CharField(max_length=100)
    phone_num = models.CharField(max_length=100)
    pub_date = models.DateTimeField()

    def __str__(self):
        return self.name

class Feedback(models.Model):
    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=100)
    writer = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    image = models.ImageField(upload_to = "feedback/", blank=True, null=True)
    email = models.CharField(max_length=100, blank=True, null=True)
    def __str__(self):
        return self.title

class Like(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Data, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        unique_together =(('user', 'post'))

class Board(models.Model):
    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=100)
    writer = models.ForeignKey(User, on_delete=models.CASCADE)
    # pub_date = models.DateTimeField()
    body = models.TextField()
    image = models.ImageField(upload_to = "board/", blank=True, null=True)
    board_like_user_set = models.ManyToManyField(User, blank=True, related_name='board_likes_user_set', through='Board_Like')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    @property
    def board_like_count(self):
        return self.board_like_user_set.count()

    def __str__(self):
        return self.title

    def title_summary(self):
        if(len(self.title) > 20):
            return self.title[:20] + "..."
        else:
            return self.title

    def summary(self):
        return self.body[:10]

class Board_Like(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Board, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        unique_together =(('user', 'post'))

class Comment_board(models.Model):
    content = models.TextField()
    writer = models.ForeignKey(User, on_delete=models.CASCADE)
    board = models.ForeignKey(Board, on_delete=models.CASCADE, related_name="board_comments")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

main/views.py
from csv import writer
from xml.etree.ElementTree import Comment
from django.shortcuts import render, redirect, get_object_or_404
from .models import Data, Request, Feedback, Like, Board, Comment_board, Board_Like
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST
from django.http import HttpResponse
import json

# Create your views here.
def showmain(request):
    datas = Data.objects.all()
    return render(request, 'main/index.html', {'datas': datas})

def introduce(request):
    return render(request, 'main/introduce.html')

def detail(request, id):
    data = get_object_or_404(Data, pk = id)
    return render(request, 'main/detail.html', {'data': data})

def create(request):
    new_data = Data()
    new_data.company = request.POST['company']
    new_data.job = request.POST['job']
    new_data.employed_year = request.POST['employed_year']
    new_data.pub_date = timezone.now() 
    new_data.body = request.POST['body']
    new_data.image = request.FILES.get('image')
    new_data.save()
    return redirect('main:detail', new_data.id)
    
def update(request, id):
    update_data = Data.objects.get(id = id)
    update_data.company = request.POST['company']
    update_data.job = request.POST['job']
    update_data.employed_year = request.POST['employed_year']
    update_data.pub_date = timezone.now() 
    update_data.body = request.POST['body']
    update_data.image = request.FILES.get('image')
    update_data.save()
    return redirect('main:detail', update_data.id)

def delete(request, id):
    delete_data = Data.objects.get(id = id)
    delete_data.delete()
    return redirect ('main:showmain')

def request_create(request):
    new_request = Request()
    new_request.employ_type = request.POST['employ_type']
    new_request.company_name = request.POST['company_name']
    new_request.school_major = request.POST['school_major']
    new_request.name = request.POST['name']
    new_request.email = request.POST['email']
    new_request.phone_num = request.POST['phone_num']
    new_request.pub_date = timezone.now()
    new_request.writer = request.user
    new_request.save()
    return redirect('main:showmain') 

def letter(request):
    return render(request, 'main/letter.html')

def board(request):
    boards = Board.objects.all().order_by('-created_at')
    return render(request, 'main/board.html', {'boards': boards})

def board_new(request):
    return render(request, 'main/board_new.html')

def board_create(request):
    new_board = Board()
    new_board.title = request.POST['title']
    new_board.writer = request.user
    new_board.pub_date = timezone.now() 
    new_board.body = request.POST['body']
    new_board.image = request.FILES.get('image')
    new_board.save()
    return redirect('main:board_detail', new_board.id)

def board_edit(request, id):
    board_edit = Board.objects.get(id = id)
    return render(request, 'main/board_edit.html', {'board': board_edit})

def board_update(request, id):
    board_update = Board.objects.get(id = id)
    board_update.title = request.POST['title']
    board_update.writer = request.user
    board_update.pub_date = timezone.now() 
    board_update.body = request.POST['body']
    board_update.image = request.FILES.get('image')
    board_update.save()
    return redirect('main:board_detail', board_update.id)

def board_detail(request, id):
    board = get_object_or_404(Board, pk = id)
    all_comments = board.board_comments.all().order_by('created_at')
    return render(request, 'main/board_detail.html', {'board': board, 'comments': all_comments})

def board_delete(request, id):
    board_delete = Board.objects.get(id = id)
    board_delete.delete()
    return redirect ('main:board')

def create_board_comment(request, board_id):
    if request.method == "POST":
        board = get_object_or_404(Board, pk=board_id)
        current_user = request.user
        comment_content = request.POST.get('content')
        Comment_board.objects.create(content=comment_content, writer=current_user, board=board)
    return redirect('main:board_detail', board_id)

def edit_board_comment(request, board_comment_id):
    edit_board_comment = Comment_board.objects.get(id = board_comment_id)
    return render(request, 'main/board_comment_edit.html', {'board_comment': edit_board_comment})

def update_board_comment(request, board_comment_id):
    update_board_comment = get_object_or_404(Comment_board, pk = board_comment_id)
    update_board_comment_writer = request.user
    update_board_comment.content = request.POST['content']
    update_board_comment.save()
    return redirect('main:board_detail', update_board_comment.board.id)

def delete_board_comment(request, board_comment_id):
    delete_board_comment = get_object_or_404(Comment_board, pk = board_comment_id)
    delete_board_comment.delete()
    return redirect('main:board_detail', delete_board_comment.board.id)

def feedback(request):
    return render(request, 'main/feedback.html')

def feedback_create(request):
    new_feedback = Feedback()
    new_feedback.title = request.POST['title']
    new_feedback.writer = request.user
    new_feedback.content = request.POST['content']
    new_feedback.image = request.FILES.get('image')
    new_feedback.email = request.POST['email']
    new_feedback.save()
    return redirect('main:showmain') 

def career(request):
    return render(request, 'main/career.html')

def sample(request):
    return render(request, 'sample/sample.html')

def board_notice(request):
    return render(request, 'main/board_notice.html')

def disallowed_useragent(request):
    return render(request, 'error/403.html')

@login_required
@require_POST

def like_toggle(request, post_id):
    post = get_object_or_404(Data, pk=post_id)
    post_like, post_like_created = Like.objects.get_or_create(user=request.user, post=post)

    if not post_like_created:
        post_like.delete()
        result = "like_cancel"
    else:
        result = "like"
    
    context = {
        "like_count":post.like_count,
        "result":result
    }

    return HttpResponse(json.dumps(context), content_type="application/json")

def board_like_toggle(request, post_id):
    post = get_object_or_404(Board, pk=post_id)
    post_like, post_like_created = Board_Like.objects.get_or_create(user=request.user, post=post)

    if not post_like_created:
        post_like.delete()
        result = "like_cancel"
    else:
        result = "like"
    
    context = {
        "like_count": post.board_like_count,
        "result": result
    }

    return HttpResponse(json.dumps(context), content_type="application/json")

main/templates/main/board.html
{% extends 'base.html' %}
{% load static %}
{% block content%}
<div id="board">
    <h1 id="board_title">자유게시판</h1>
    <h4 id="board_subtitle">자유게시판에서 질문과 답변을 통해 서로의 정보를 공유해 봅시다.</h4>
    <table id="board_table">
        <thead id="board_table_head">
            <tr>
                <th id="board_table_head_number" class="board_table_heads">번호</th>
                <th id="board_table_head_title" class="board_table_heads">제목</th>
                <th id="board_table_head_writer" class="board_table_heads">작성자</th>
                <th id="board_table_head_pubdate" class="board_table_heads">작성일자</th>
                <th id="board_table_head_like" class="board_table_heads">추천수</th>
            </tr>
        </thead>
        <tbody id="board_table_body">
            <tr id="board_table_body_content">
                <td id="board_table_body_number" class="board_table_bodies">공지</td>
                <td id="board_table_body_title" class="board_table_bodies"><a href="{% url 'main:board_notice' %}">자유게시판 안내</a></td>
                <td id="board_table_body_writer" class="board_table_bodies">관리자</td>
                <td id="board_table_body_pubdate" class="board_table_bodies">-</td>   
                <td id="board_table_body_like" class="board_table_bodies">-</td>             
            </tr>
            {% for board in boards %}
            <tr id="board_table_body_content">
                <td id="board_table_body_number" class="board_table_bodies">{{forloop.revcounter}}</td>
                <td id="board_table_body_title" class="board_table_bodies"><a href="{% url 'main:board_detail' board.id %}">{{board.title_summary}}</a></td>
                <td id="board_table_body_writer" class="board_table_bodies">{{board.writer}}</td>
                <td id="board_table_body_pubdate" class="board_table_bodies">{{board.created_at}}</td>
                <td id="board_table_body_like" class="board_table_bodies">{{board.board_like_count}}</td>             
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <br>
    <button id="board_create_button" onclick="location.href = '{% url 'main:board_new' %}'">글 작성하기</button>
</div>
{% endblock %}

main/templates/main/board_comment.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div id="board_comment_edit">
    <h1>댓글 수정하기</h1>
    <div>
        <form action="{% url 'main:update_board_comment' board_comment.id %}" method="POST">
            {% csrf_token %}
            <input type="text" name='content' placeholder="댓글내용입력" id="comment_create_input" value="{{board_comment.content}}">
            <input type="submit" value="확인">
        </form>
    </div>
</div>
{% endblock%}

main/templates/main/board_detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div id="board_detail">
	<div>
		<h1 id="board_detail_title">{{board.title}}</h1>
		<div id="board_detail_info">
			<p id="board_detail_writer">{{board.writer}}</p>
			<p id="board_detail_pubdate">최종 수정일자: {{board.updated_at}}</p>
		</div>
		<div id="board_detail_content">
			<textarea disabled>{{board.body}}</textarea>
			{% if board.image %}
				<img id="board_detail_image" src="{{board.image.url}}" alt="사진">
			{% endif %}
		</div>
	</div>
	<div id="board_detail_function">
		{% if user == board.writer %}
		<a href="{% url 'main:board_edit' board.id %}"><button>글 수정</button></a>
		<a href="{% url 'main:board_delete' board.id %}"><button>글 삭제</button></a>
		{% endif %}
		<a href="{% url 'main:board' %}"><button>게시판으로 돌아가기</button></a>
		<br>
		<div id="board_detail_function_like">
			<button id="board_detail_function_like_button" href="#" class="like" name="{{board.title}}" value="Like">
				{% if user in board.board_like_user_set.all %}
				<div class="alt-service-icon">
					<i class="fas fa-thumbs-up fa-lg" id="recommend-icon"></i>
				</div>
				{% else %}
				<div class="alt-service-icon">
					<i class="far fa-thumbs-up fa-lg" id="recommend-icon"></i>
				</div>
				{% endif %}
				<h4 id="count-{{board.id}}_like" class="alt-services-title font-alt">
					&nbsp;추천
					{% if board.board_like_count == 0 %}
					0개
					{% else %}
					{{board.board_like_count}}개
					{% endif %}
				</h4>
			</button>
		</div>
	</div>
	<div id="board_detail_comment">
		{% if comments %}
		<h1 id="board_detail_comment_title">댓글목록</h1>
		{% for comment in comments %}
		<div id="board_detail_comment_content">
			<div id="board_detail_comment_content_box">
				<p>{{comment.writer}}</p>
				<div>
					<a class="board_comment_answer_button"><button>답글</button></a>
					{% if user == comment.writer %}
					<a href="{% url 'main:edit_board_comment' comment.id %}"><button>댓글 수정</button></a>
					<a href="{% url 'main:delete_board_comment' comment.id %}"><button>댓글 삭제</button></a>
					{% endif %}
				</div>
			</div>
			<p>{{comment.content}}</p>
		</div>
		{% endfor %}
		{% endif %}
		<div id="board_detail_comment_create">
			{% if user.is_authenticated %}
			<h4>댓글쓰기</h4>
			<form action="{% url 'main:create_board_comment' board.id%}" method="POST">
				{%csrf_token%}
				<input id="comment_create_input" type="text" name="content" placeholder="댓글내용입력">
				<input type="submit" value="등록">
			</form>
			{% else %}
			<p>로그인 후 댓글 작성 가능</p>
			{% endif %}
		</div>
	</div>
</div>
{% if user.is_authenticated %}
<script src="{% static 'js/board_detail.js' %}"></script>
{% endif%}
<script>
    $(".like").click(function(){
        var pk = $(this).attr('name')
        $.ajax({
            url : "{% url 'main:board_like_toggle' board.pk %}",
            data : {'pk':pk,'csrfmiddlewaretoken': '{{ csrf_token }}'},
            type:"POST",
            dataType:"json",
            
            success: function(response){
                if (response.like_count==null){
                    alert("로그인이 필요합니다.");
                    window.location.replace('/accounts/login/')
                }
                else{
                    if (response.result == "like"){
                        $('#recommend-icon').removeClass();
                        $('#recommend-icon').addClass('fas fa-thumbs-up fa-lg');
                    }
                    else{
                        $('#recommend-icon').removeClass();
                        $('#recommend-icon').addClass('far fa-thumbs-up fa-lg');
                    }
                    $('#count-{{ board.id }}_like').html('&nbsp;추천 '+response.like_count+'개');
                }
            },
            error: function(request, status, error){
                alert("로그인이 필요합니다.")
	            alert("code:"+request.status+"\n"+"message:"+request.responseText+"\n"+"error:"+error); 
        	},
         });
    })
 </script>
{% endblock %}

main/templates/main/board_edit.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div id="board_new">
	<h1>글 수정하기</h1>
	<form action = "{% url 'main:board_update' board.id %}" method = "post" enctype="multipart/form-data">
    	{% csrf_token %}
    	<p>제목<br><br><input type="text" name="title" value="{{board.title}}" id="board_new_input_title"></p>
		<p>내용<br><br><textarea name="body" id="board_new_input_content">{{board.body}}</textarea></p>
        <p>사진: <input type="file" name="image" value=""></p>
        <div id="board_new_button_submit">
			<button type="submit">등록</button>
		</div >
	</form>
</div>
{% endblock %}

main/templates/main/board_new.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div id="board_new">
	<h1>글 작성하기</h1>
	<form action = "{% url 'main:board_create' %}" method = "post" enctype="multipart/form-data">
    	{% csrf_token %}
    	<p>제목<br><br><input id="board_new_input_title" type="text" name="title"></p>
		<p>내용<br><br><textarea id="board_new_input_content" name="body"></textarea></p>
        <p>사진: <input type="file" name="image"></p>
		<div id="board_new_button_submit">
			<button type="submit">등록</button>
		</div >
	</form>
</div>
{% endblock %}

main/templates/main/board_notice.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div id="board_detail">
	<div>
		<h1 id="board_detail_title">공지사항</h1>
		<div id="board_detail_info">
			<p id="board_detail_writer">관리자</p>
			<p id="board_detail_pubdate"></p>
		</div>
		<div id="board_detail_content">
			<textarea disabled>
안녕하세요. NODOUBT의 관리자입니다.

모두가 자유롭게 이용하여 취업에 도움이 되었으면 하는 조그만 소망으로 게시판을 개설하였습니다.

취업에 대한 정보, 고민, 질문 등...
취업과 관련된 내용이면 무엇이든지 좋습니다.

다만, 모두가 이용하는 공간인 만큼 상대방을 배려해주시면 감사하겠습니다.

언젠가, 밝게 빛나게 될 당신의 앞길에 조금이나마 도움이 되었으면 합니다.
			</textarea>
		</div>
	</div>
	<div id="board_detail_function">
		<a href="{% url 'main:board' %}"><button>게시판으로 돌아가기</button></a>
	</div>	
</div>
{% endblock %}

main/templates/main/detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

{% if user.is_authenticated %}
<!-- 선배들의 취업 정보 상세 -->
<br><br>
<div id="detail_head">
    <div class="loader"></div>
</div>
<div id="detail_body">{{data.body}}</div>
<div id="detail_tail">
    <h1 id="detail_tail_title">선배님의 정보가 도움이 되었다면?</h1>
    <span href="#" class="like" name="{{data.company}}" value="Like">
        {% if user in data.like_user_set.all %}
        <div class="alt-service-icon">
            <i class="fas fa-heart fa-3x" id="like-icon"></i>
        </div>
        {% else %}
        <div class="alt-service-icon">
            <i class="far fa-heart fa-3x" id="like-icon"></i>
        </div>
        {% endif %}
        <h3 id="count-{{data.id}}_like" class="alt-services-title font-alt">
            좋아요
            {% if data.like_count == 0 %}
            0개
            {% else %}
            {{data.like_count}}개
            {% endif %}
        </h3>
    </span>
    <a href="{% url 'main:showmain' %}"><button id="detail_tail_button">홈으로 돌아가기</button></a>
</div>
<br><br><br><br>
{% else %}
<div id="detail_tail_login">
    <div>
        <h4>로그인 후 이용 가능</h4>
        <a href="{% url 'account_login' %}"><button id="detail_tail_login_button">구글 로그인</button></a>
    </div>
</div>
{% endif %}
{% if user.is_authenticated %}
<script src="{% static 'js/detail.js' %}"></script>
{% endif %}
<script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
<script>
    $(".like").click(function(){
        var pk = $(this).attr('name')
        $.ajax({
            url : "{% url 'main:like_toggle' data.pk %}",
            data : {'pk':pk,'csrfmiddlewaretoken': '{{ csrf_token }}'},
            type:"POST",
            dataType:"json",
            
            success: function(response){
                if (response.like_count==null){
                    alert("로그인이 필요합니다.");
                    window.location.replace('/accounts/login/')
                }
                else{
                    if (response.result == "like"){
                        $('#like-icon').removeClass();
                        $('#like-icon').addClass('fas fa-heart fa-3x');
                    }
                    else{
                        $('#like-icon').removeClass();
                        $('#like-icon').addClass('far fa-heart fa-3x');
                    }
                    $('#count-{{ data.id }}_like').html('좋아요 '+response.like_count+'개');
                }
            },
            error: function(request, status, error){
                alert("로그인이 필요합니다.")
	            alert("code:"+request.status+"\n"+"message:"+request.responseText+"\n"+"error:"+error); 
        	},
         });
    })
 </script>
{% endblock %}

main/templates/main/feedback.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<!-- 피드백 / 요청사항 작성 -->
<div id="feedback">
	<h1>피드백 / 요청사항</h1>
	{% if user.is_authenticated %}
	<h4>※ 제목과 내용은 필수적으로 작성해주셔야 합니다.</h4>
	<form action = "{% url 'main:feedback_create' %}" method = "post" enctype="multipart/form-data">
    	{% csrf_token %}
    	<p>제목: <input required type="text" name="title" size="30"></p>
    	<p>내용: <textarea required type="text" name="content" id="" cols="31" rows="4"></textarea></p>
    	<p>첨부파일: <input type="file" name="image"></p>
    	<p>답변을 받을 이메일: <input type="text" name="email" size="30"></p>
		<br>
		<div id="feedback_submit">
			<button type="submit">제출</button>
		</div>
	</form>
	{% else %}
	<div id="feedback_notlogin">
		<h2 id="feedback_signup">구글 로그인 후 가능</h4>
		<a href="{% url 'account_login' %}"><button>구글 로그인</button></a>
	</div>	
	{% endif %}
</div>
{% endblock %}

main/templates/main/letter.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<!-- 개인정보 처리 방침 -->
<div id="letter">
    &nbsp;안녕하세요! 저희는 경영학부 15학번 및 16학번으로 구성된 NODOUBT 팀입니다. 저희 서비스가 드리는 사용자분들과의 약속입니다.<br><br>
    1. 개인정보의 처리 목적<br>&nbsp;(‘http://nodoubt.site/’ 이하 ‘NODOUBT’) 은(는) 자체 컨텐츠 제공의 목적을 위하여 개인정보를 처리하고 있으며, 그 외의 용도로는 이용하지 않습니다.<br><br>
    2. 정보주체와 법정대리인의 권리·의무 및 그 행사방법 이용자는 개인정보주체로써 다음과 같은 권리를 행사할 수 있습니다.<br>
    정보주체는 NODOUBT에 대해 언제든지 다음 각 호의 개인정보 보호 관련 권리를 행사할 수 있습니다.<br>
    &nbsp;(1) 개인정보 열람요구<br>
    &nbsp;(2) 오류 등이 있을 경우 정정 요구<br>
    &nbsp;(3) 삭제요구<br>
    &nbsp;(4) 처리정지 요구<br><br>
    3. 처리하는 개인정보의 항목 작성<br>
    &nbsp;NODOUBT는 다음의 개인정보 항목을 처리하고 있습니다.<br>
    - 필수항목: 이름, 학번, 이메일<br><br>
    4. 개인정보의 파기는 원칙적으로 개인정보 처리목적이 달성된 경우에는 지체없이 해당 개인정보를 파기합니다. 파기의 절차 및 방법은 다음과 같습니다.<br>
    &nbsp;이용자가 입력한 정보는 목적 달성 후 별도의 DB에 옮겨져 (종이의 경우 별도의 서류) 내부 방침 및 기타 관련 법령에 따라 일정 기간 저장된 후 혹은 즉시 파기됩니다. 이 때, DB로 옮겨진 개인정보는 법률에 의한 경우가 아니고서는 다른 목적으로 이용되지 않습니다.<br><br>
    5. 개인정보 보호책임자 작성<br>
    &nbsp;NODOUBT는 개인정보 처리에 관한 업무를 총괄해서 책임지고, 개인정보 처리와 관련한 정보주체의 불만처리 및 피해구제 등을 위하여 아래와 같이 개인정보 보호책임자를 지정하고 있습니다.<br><br>
    ▶ 개인정보 보호책임자<br>성명: 허윤회<br>연락처: dbsghl123@naver.com<br><br>
    &nbsp;정보주체께서는 NODOUBT의 서비스(또는 사업)을 이용하시면서 발생한 모든 개인정보 보호 관련 문의, 불만처리, 피해구제 등에 관한 사항을 개인정보 보호 책임자에 문의하실 수 있습니다. NODOUBT는 정보주체의 문의에 대해 지체 없이 답변 및 처리해드릴 것입니다.<br><br>
    <div class="letter_center">
        <a href="{% url 'main:feedback' %}"><button>피드백 및 요청사항 남기기</button></a><br><br>
    </div>
    <div class="letter_center">- NODOUBT 드림 -</div>
</div>
{% endblock %}